services:
  - type: web
    name: roommatch
    env: php
    buildCommand: composer install --no-dev && php artisan config:cache && php artisan route:cache
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false